name: 'Test'

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  TEST_REPO: https://github.com/jasonyang-ee/STM32-CMAKE-TEMPLATE.git

jobs:
  Build_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Docker meta ubuntu
      id: meta-ubuntu
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu
        tags: |
          type=ref,event=tag

    - name: Docker meta alpine
      id: meta-alpine
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine
        tags: |
          type=ref,event=tag

    - name: Build Push for Ubuntu
      id: output-ubuntu
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        push: false
        load: true
        tags: ${{ steps.meta-ubuntu.outputs.tags }}
        labels: ${{ steps.meta-ubuntu.outputs.labels }}

    - name: Build Push for Alpine
      id: output-alpine
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.alpine
        push: false
        load: true
        tags: ${{ steps.meta-alpine.outputs.tags }}
        labels: ${{ steps.meta-alpine.outputs.labels }}

    - name: Test
      run: |
        docker run ${{ steps.output-ubuntu.imageid }} ${{ env.TEST_REPO }}