name: 'Build and Push to Docker Hub'

on:
  push:
    tags:
      - '*'

jobs:
  Build_Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Push for Ubuntu
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        push: true
        tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu:$GITHUB_REF_NAME
              ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu:latest

    - name: Build Push for Alpine
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.alpine
        push: true
        tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine:$GITHUB_REF_NAME
              ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine:$latest