name: 'Test'

on:
  push:
    branches:
      - 'main'

env:
  TEST_REPO: https://github.com/jasonyang-ee/STM32-CMAKE-TEMPLATE.git

jobs:
  Build_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Checkout example repo
      uses: actions/checkout@v3
      with:
        repository: jasonyang-ee/STM32-CMAKE-TEMPLATE
        path: project
      
    - name: Docker meta ubuntu
      id: meta-ubuntu
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu
        tags: type=ref,event=branch

    - name: Docker meta alpine
      id: meta-alpine
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine
        tags: type=ref,event=branch

    - name: Build and Load for Ubuntu
      id: output-ubuntu
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ github.workspace }}/Dockerfile.ubuntu
        push: false
        load: true
        tags: ${{ steps.meta-ubuntu.outputs.tags }}
        labels: ${{ steps.meta-ubuntu.outputs.labels }}

    - name: Build and Load for Alpine
      id: output-alpine
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ github.workspace }}/Dockerfile.alpine
        push: false
        load: true
        tags: ${{ steps.meta-alpine.outputs.tags }}
        labels: ${{ steps.meta-alpine.outputs.labels }}

    - name: Test Ubuntu URL
      run: |
        docker run ${{ steps.output-ubuntu.outputs.imageid }} ${{ env.TEST_REPO }}

    - name: Test Alpine URL
      run: |
        docker run ${{ steps.output-alpine.outputs.imageid }} ${{ env.TEST_REPO }}

    - name: Test Ubuntu Volume
      run: docker run -v "${{ github.workspace }}/project":"/build" ${{ steps.output-ubuntu.outputs.imageid }}

    - name: Test Ubuntu Volume
      run: docker run -v "${{ github.workspace }}/project":"/build" ${{ steps.output-alpine.outputs.imageid }}