name: 'Test'

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  TEST_REPO: https://github.com/jasonyang-ee/STM32-CMAKE-TEMPLATE.git

jobs:
  Build_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: main

    - name: Checkout example repo
      uses: actions/checkout@v3
        with:
          repository: jasonyang-ee/STM32-CMAKE-TEMPLATE
          path: project
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu
        tags: type=ref,event=branch

    - name: Build and Load for Ubuntu
      id: result
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ github.workspace }}/main/Dockerfile.ubuntu
        push: false
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Test Ubuntu
      run: docker run ${{ steps.result.outputs.imageid }} ${{ env.TEST_REPO }}

    - name: Test Ubuntu
      run: docker run -v "${{ github.workspace }}/project":"/build" ${{ steps.result.outputs.imageid }}
