name: 'Build'

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  Build_Upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Docker meta ubuntu
      id: meta-ubuntu
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu
        tags: |
          type=ref,event=tag

    - name: Docker meta alpine
      id: meta-alpine
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine
        tags: |
          type=ref,event=tag

    - name: Build Push for Ubuntu
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        push: false
        tags: ${{ steps.meta-ubuntu.outputs.tags }}
        labels: ${{ steps.meta-ubuntu.outputs.labels }}

    - name: Build Push for Alpine
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.alpine
        push: false
        tags: ${{ steps.meta-alpine.outputs.tags }}
        labels: ${{ steps.meta-alpine.outputs.labels }}