on:
  push:
    tags:
      - "*"

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Build Ubuntu
      run: |
        docker build -t stm32_ubuntu:latest Ubuntu/.

    - name: Build Alpine
      run: |
        docker build -t stm32_alpine:latest Alpine/.
