name: 'Test'

on:
  push:
    branches:
      - "*"
      - "!main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  TEST_REPO_URL: https://github.com/jasonyang-ee/STM32-CMAKE-TEMPLATE.git
  TEST_REPO: jasonyang-ee/STM32-CMAKE-TEMPLATE

jobs:
  Build_Test_AMD64:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        files: [ubuntu, debian, alpine, arch]

    steps:
    - name: free disk space from docker
      run: |
        docker rmi $(docker image ls -aq)
        df -h

    - name: Checkout project
      uses: actions/checkout@v3

    - name: Checkout example repo
      uses: actions/checkout@v3
      with:
        repository: jasonyang-ee/STM32-CMAKE-TEMPLATE
        path: project-${{ matrix.files }}-amd64

    - name: Set QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Load
      id: build3x
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        file: ${{ github.workspace }}/Dockerfile.${{ matrix.files }}
        load: true
        tags: stm32-builder/${{ matrix.files }}-test

    - name: Test
      run: |
        docker run --rm ${{ steps.build3x.outputs.imageid }} ${{ env.TEST_REPO_URL }}
        docker run --rm -v "${{ github.workspace }}/project-${{ matrix.files }}-amd64":"/proj" ${{ steps.build3x.outputs.imageid }} /proj-${{ matrix.files }}-amd64
        docker run --rm -v "${{ github.workspace }}/hybrid-${{ matrix.files }}-amd64":"/home" ${{ steps.build3x.outputs.imageid }} ${{ env.TEST_REPO_URL }} Debug

    - name: Cleanup Folders
      run: |
        sudo rm -r ${{ github.workspace }}/project-*
        sudo rm -r ${{ github.workspace }}/hybrid-*

  Build_Test_ARM64:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        files: [ubuntu, debian, alpine]

    steps:
    - name: free disk space from docker
      run: |
        docker rmi $(docker image ls -aq)
        df -h

    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Only
      id: build3x
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64
        file: ${{ github.workspace }}/Dockerfile.${{ matrix.files }}
        tags: stm32-builder/${{ matrix.files }}-test

  Result:
    runs-on: ubuntu-22.04
    needs:
      - Build_Test_AMD64
      - Build_Test_ARM64
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
