on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: stm32_ubuntu:latest
          outputs: type=docker,dest=/Ubuntu/stm32_ubuntu.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stm32_ubuntu
          path: /Ubuntu/stm32_ubuntu.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: stm32_ubuntu
          path: /Ubuntu
      -
        name: Load image
        run: |
          docker load --input /Ubuntu/stm32_ubuntu.tar
          docker image ls -a
