name: 'Upload'

on:
  push:
    tags:
      - '*'

jobs:
  Build_Upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Docker meta ubuntu
      id: meta-ubuntu
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_ubuntu
          ${{ vars.REGISTRY }}/stm32_ubuntu
        tags: type=ref,event=tag

    - name: Docker meta alpine
      id: meta-alpine
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32_alpine
          ${{ vars.REGISTRY }}/stm32_alpine
        tags: type=ref,event=tag

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Github Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.USER_GITHUB_PERSONAL }}
        password: ${{ secrets.TOKEN_GITHUB_PERSONAL }}

    - name: Build and Upload for Ubuntu
      id: output-ubuntu
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ github.workspace }}/Dockerfile.ubuntu
        push: true
        tags: ${{ steps.meta-ubuntu.outputs.tags }}
        labels: ${{ steps.meta-ubuntu.outputs.labels }}

    - name: Build and Upload for Alpine
      id: output-alpine
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ github.workspace }}/Dockerfile.alpine
        push: true
        tags: ${{ steps.meta-alpine.outputs.tags }}
        labels: ${{ steps.meta-alpine.outputs.labels }}