name: 'Upload'

on:
  push:
    tags:
      - '*'

jobs:
  Build_Upload:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        files: [ubuntu, debian, alpine, arch]

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stm32-builder
          ${{ vars.REGISTRY }}/stm32-builder
        tags: type=ref,event=tag
        flavor: prefix=${{ matrix.files }}-,onlatest=true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Github Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.USER_GITHUB_PERSONAL }}
        password: ${{ secrets.TOKEN_GITHUB_PERSONAL }}

    # - uses: actions/delete-package-versions@v4
    #   with: 
    #     package-name: 'stm32-builder'
    #     package-type: 'container'
    #     min-versions-to-keep: 0
    #     delete-only-untagged-versions: 'true'

    - name: Set QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Upload amd64 and arm64
      if: ${{ matrix.files != 'arch'}} && ${{ matrix.files != 'alpine'}}
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ${{ github.workspace }}/Dockerfile.${{ matrix.files }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
    - name: Build and Upload amd64
      if: ${{ matrix.files == 'arch'}} && ${{ matrix.files == 'alpine'}}
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        file: ${{ github.workspace }}/Dockerfile.${{ matrix.files }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}